global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "leobrain-api"
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'api'